import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PraciceModal } from "@/components/modals/practice-modal";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { Providers } from "@/components/providers"; 
import { LanguageSwitcher } from "@/components/language-switcher"; 
import { ClientOnly } from "@/components/client-only";
import TopRightWidgets from "@/components/TopRightWidgets";
import { FontSizeProvider } from "@/components/FontSizeSelector";
import AdminShortcut from "@/components/admin-shortcut";
import BackToHome from "@/components/admin-shortcut/back-to-home";


const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learning Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="./logo_main.svg" sizes="any" />
        </head>
        <body className={`${font.className} bg-background text-foreground`}>
          <Providers>
          <FontSizeProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {/* Chỉ hiện TopRightWidgets ở desktop (>=640px) */}
          <div className="hidden sm:block">
            <TopRightWidgets />
          </div>
          <Toaster />
          <BackToHome />
          <AdminShortcut />
          <ExitModal />
          <HeartsModal />
          <PraciceModal />
          {children}
          </ThemeProvider>
          </FontSizeProvider>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}